tm_solution_entity_analyzer_test:
    resource: "@TMSolutionEntityAnalyzerBundle/Resources/config/routing/product.yml"
    prefix:   /test

tm_solution_entity_analyzer_homepage:
    path:     /
    defaults: { _controller: TMSolutionEntityAnalyzerBundle:Default:index }
