services:
    prototype.controller:
        class: TMSolution\EntityAnalyzerBundle\Controller\PrototypeController
        arguments: ["@service_container"]
        shared: false
        
        
    prototype.config:
        class: TMSolution\EntityAnalyzerBundle\Service\PrototypeConfig
        arguments: ["@service_container"]
        shared: false    