menuitem_index:
    path:     /
    defaults: { _controller: "TMSolutionMenuBundle:MenuItem:index" }
    methods:  GET

menuitem_show:
    path:     /{id}/show
    defaults: { _controller: "TMSolutionMenuBundle:MenuItem:show" }
    methods:  GET

menuitem_new:
    path:     /new
    defaults: { _controller: "TMSolutionMenuBundle:MenuItem:new" }
    methods:  [GET, POST]

menuitem_edit:
    path:     /{id}/edit
    defaults: { _controller: "TMSolutionMenuBundle:MenuItem:edit" }
    methods:  [GET, POST]

menuitem_delete:
    path:     /{id}/delete
    defaults: { _controller: "TMSolutionMenuBundle:MenuItem:delete" }
    methods:  DELETE
