
tm_solution_sandbox_test:
    path: "test"
    defaults: { _controller: "tm_solution_prototype.test_controller:testAction",  format: ~ }
    methods:  [GET, POST]
    options:
        expose: true    
