flexix_mapper:
    applications:
        admin:
            bundles:
                - flexix_sample_entities
            name: admin
        api:
            bundles:
                - flexix_sample_entities
            name: api
        wizard:
            bundles:
                - flexix_wizard
            name: wizard
            
        menu:
            bundles:
                - flexix_menu
            name: menu    
    entities:
        gedmo_lo:
            log_entry:
                alias: log-entry
                entity_class: Gedmo\Loggable\Entity\LogEntry
        gedmo_loggable:
            abstract_log_entry:
                alias: abstract-log-entry
                entity_class: Gedmo\Loggable\Entity\MappedSuperclass\AbstractLogEntry
        gedmo_tran:
            translation:
                alias: translation
                entity_class: Gedmo\Translator\Entity\Translation
        gedmo_transl:
            translation:
                alias: translation
                entity_class: Gedmo\Translatable\Entity\Translation
        gedmo_translatable:
            abstract_personal_translation:
                alias: abstract-personal-translation
                entity_class: Gedmo\Translatable\Entity\MappedSuperclass\AbstractPersonalTranslation
            abstract_translation:
                alias: abstract-translation
                entity_class: Gedmo\Translatable\Entity\MappedSuperclass\AbstractTranslation
        gedmo_tree:
            abstract_closure:
                alias: abstract-closure
                entity_class: Gedmo\Tree\Entity\MappedSuperclass\AbstractClosure
        flexix_menu:
            menu_item:
                alias: menu-item
                entity_class: Flexix\MenuBundle\Entity\MenuItem
        flexix_sample_entities:
            discount:
                alias: discount
                entity_class: Flexix\SampleEntitiesBundle\Entity\Discount
            measure_unit:
                alias: measure-unit
                entity_class: Flexix\SampleEntitiesBundle\Entity\MeasureUnit
            payment_frequency:
                alias: payment-frequency
                entity_class: Flexix\SampleEntitiesBundle\Entity\PaymentFrequency
            product:
                alias: product
                entity_class: Flexix\SampleEntitiesBundle\Entity\Product
            product_category:
                alias: product-category
                entity_class: Flexix\SampleEntitiesBundle\Entity\ProductCategory
            product_definition:
                alias: product-definition
                entity_class: Flexix\SampleEntitiesBundle\Entity\ProductDefinition
            product_dictionary:
                alias: product-dictionary
                entity_class: Flexix\SampleEntitiesBundle\Entity\ProductDictionary
            product_price:
                alias: product-price
                entity_class: Flexix\SampleEntitiesBundle\Entity\ProductPrice
            transaction:
                alias: transaction
                entity_class: Flexix\SampleEntitiesBundle\Entity\Transaction
            transaction_status:
                alias: transaction-status
                entity_class: Flexix\SampleEntitiesBundle\Entity\TransactionStatus
            transaction_type:
                alias: transaction-type
                entity_class: Flexix\SampleEntitiesBundle\Entity\TransactionType
        flexix_wizard:
            view_configuration:
                alias: view-configuration
                entity_class: Flexix\WizardBundle\Entity\ViewConfiguration
            view_type:
                alias: view-type
                entity_class: Flexix\WizardBundle\Entity\ViewType
