tm_solution_mapper:
    applications:
        admin:
            bundles:
                - tm_solution_sample_entities
            name: admin
        api:
            bundles:
                - tm_solution_sample_entities
            name: api
    entities:
        tm_solution_sample_entities:
            discount:
                alias: discount
                entityClass: TMSolution\SampleEntitiesBundle\Entity\Discount
            measure_unit:
                alias: measure-unit
                entityClass: TMSolution\SampleEntitiesBundle\Entity\MeasureUnit
            payment_frequency:
                alias: payment-frequency
                entityClass: TMSolution\SampleEntitiesBundle\Entity\PaymentFrequency
            product:
                alias: product
                entityClass: TMSolution\SampleEntitiesBundle\Entity\Product
            product_category:
                alias: product-category
                entityClass: TMSolution\SampleEntitiesBundle\Entity\ProductCategory
            product_definition:
                alias: product-definition
                entityClass: TMSolution\SampleEntitiesBundle\Entity\ProductDefinition
            product_dictionary:
                alias: product-dictionary
                entityClass: TMSolution\SampleEntitiesBundle\Entity\ProductDictionary
            product_price:
                alias: product-price
                entityClass: TMSolution\SampleEntitiesBundle\Entity\ProductPrice
            transaction:
                alias: transaction
                entityClass: TMSolution\SampleEntitiesBundle\Entity\Transaction
            transaction_status:
                alias: transaction-status
                entityClass: TMSolution\SampleEntitiesBundle\Entity\TransactionStatus
            transaction_type:
                alias: transaction-type
                entityClass: TMSolution\SampleEntitiesBundle\Entity\TransactionType
