
flexix_menu:
    resource: "@FlexixMenuBundle/Resources/config/routing.yml"
    prefix:   /



flexix_form_type_templates:
    resource: "@FlexixFormTypeTemplatesBundle/Resources/config/routing.yml"
    prefix:   /

flexix_generator:
    resource: "@FlexixGeneratorBundle/Resources/config/routing.yml"
    prefix:   /

flexix_sandbox:
    resource: "@FlexixSandboxBundle/Resources/config/routing.yml"
    prefix:   /

flexix_sample_entities_product_category:
    resource: "@FlexixSampleEntitiesBundle/Controller/ProductCategoryController.php"
    type:     annotation

flexix_prototype:
    resource: "@FlexixPrototypeBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

