
tm_solution_menu:
    resource: "@TMSolutionMenuBundle/Resources/config/routing.yml"
    prefix:   /



tm_solution_form_type_templates:
    resource: "@TMSolutionFormTypeTemplatesBundle/Resources/config/routing.yml"
    prefix:   /

tm_solution_generator:
    resource: "@TMSolutionGeneratorBundle/Resources/config/routing.yml"
    prefix:   /

tm_solution_sandbox:
    resource: "@TMSolutionSandboxBundle/Resources/config/routing.yml"
    prefix:   /

tm_solution_sample_entities_product_category:
    resource: "@TMSolutionSampleEntitiesBundle/Controller/ProductCategoryController.php"
    type:     annotation

tm_solution_prototype:
    resource: "@TMSolutionPrototypeBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

