tm_solution_sample_entities:
    resource: "@TMSolutionSampleEntitiesBundle/Resources/config/routing.yml"
    prefix:   /

tm_solution_class_mapper:
    resource: "@TMSolutionClassMapperBundle/Resources/config/routing.yml"
    prefix:   /

tm_solution_entity_analyzer:
    resource: "@TMSolutionEntityAnalyzerBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

# app/config/routing.yml
fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"