security:
    
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
    
    firewalls:
                
        
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                # if you are using Symfony < 2.8, use the following config instead:
                # csrf_provider: form.csrf_provider

            logout:       true
            anonymous:    true
        
        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false
            
        oauth_authorize:
            pattern:    ^/oauth/v2/auth
            http_basic: ~    

#        oauth_authorize:
#            pattern:    ^/oauth/v2/auth
#            form_login:
#                provider: user_provider
#                check_path: vp_global_login_check
#                login_path: vp_global_login
#            anonymous: true
#            context: test_connect
            
            #provider: fos_userbundle
            # Add your favorite authentication process here

        api:
            pattern:    ^/api
            fos_oauth:  true
            stateless:  true
            anonymous:  false # can be omitted as its default value


    access_control:
        - { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ] }       