# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    tm_solution_menu.sample_menu_builder:
        class: TMSolution\MenuBundle\Menu\MenuBuilder
        arguments: ['@knp_menu.factory','@doctrine.orm.entity_manager','main']

    tm_solution_menu.main_menu:
        class: Knp\Menu\MenuItem 
        factory: ['@tm_solution_menu.sample_menu_builder', createMainMenu]
        arguments: ["@request_stack"]
        tags:
            - { name: knp_menu.menu, alias: main }