services:
    
    tm_solution_prototype.application_mapper:
        class: TMSolution\MapperBundle\Util\ApplicationMapper     
        arguments: [%tm_solution_mapper.applications%]
      
    tm_solution_prototype.entity_mapper: 
        class: TMSolution\MapperBundle\Util\EntityMapper
        arguments: [%tm_solution_mapper.entities%]
    
    tm_solution_prototype.request_analyzer:
        class: TMSolution\RequestAnalyzerBundle\Util\RequestAnalyzer
        arguments: ['@tm_solution_prototype.application_mapper', '@tm_solution_prototype.entity_mapper']
    
    tm_solution_prototype.base_configuration:
        class: TMSolution\ConfigurationBundle\Util\Configuration
        arguments: [%tm_solution_prototype.configuration%]
    
    tm_solution_prototype.configuration_factory:
        class: TMSolution\ControllerConfigurationBundle\Util\ControllerConfigurationFactory
        arguments: ['@tm_solution_prototype.base_configuration','@tm_solution_prototype.request_analyzer']

   
    tm_solution_prototype.data_adapter:
        class: TMSolution\PrototypeBundle\Util\DataAdapter
   
   
    tm_solution_prototype.entity_controller:
        class: TMSolution\PrototypeBundle\Controller\EntityController
        arguments: ['@service_container','@tm_solution_prototype.configuration_factory','@request_stack','@tm_solution_prototype.data_adapter']
        
        
    tm_solution_prototype.test_controller:
        class: TMSolution\PrototypeBundle\Controller\TestController
        arguments: ['@service_container','@tm_solution_prototype.configuration_factory','@request_stack','@tm_solution_prototype.data_adapter']    
        
    tm_solution_prototype.test_controller:
        class: TMSolution\PrototypeBundle\Controller\TestController
        arguments: ['@service_container','@tm_solution_prototype.configuration_factory']

        
    tm_solution_prototype.ticket:
        class: TMSolution\PrototypeBundle\Util\Ticket
        arguments: []       
        shared: false
            
 
            
      