parameters:
    
    test.configuration:
        actions: 
            new:
                allowed: true
                formTypeClass: 'TMSolution\SampleEntitiesBundle\Form\ProductCategoryType'
                templates:
                    element: 'productcategory\new.html.twig'
                
services:
    
    tm_solution_prototype.application_mapper:
        class: TMSolution\MapperBundle\Util\ApplicationMapper     
        arguments: [%tm_solution_mapper.applications%]
      
    tm_solution_prototype.entity_mapper: 
        class: TMSolution\MapperBundle\Util\EntityMapper
        arguments: [%tm_solution_mapper.entities%]
    
    tm_solution_prototype.request_analyzer:
        class: TMSolution\RequestAnalyzerBundle\Util\RequestAnalyzer
        arguments: ['@tm_solution_prototype.application_mapper', '@tm_solution_prototype.entity_mapper']
    
    tm_solution_prototype.base_configuration:
        class: TMSolution\ConfigurationBundle\Util\Configuration
        arguments: [%tm_solution_prototype.configuration%]
    
    tm_solution_prototype.configuration_factory:
        class: TMSolution\ControllerConfigurationBundle\Util\ControllerConfigurationFactory
        arguments: ['@tm_solution_prototype.base_configuration','@tm_solution_prototype.request_analyzer']
   
    tm_solution_prototype.prototype_controller:
        class: TMSolution\PrototypeBundle\Controller\PrototypeController
        arguments: ['@service_container','@tm_solution_prototype.configuration_factory']
        
    tm_solution_prototype.test_controller:
        class: TMSolution\PrototypeBundle\Controller\TestController
        arguments: ['@service_container','@tm_solution_prototype.configuration_factory']    


    tm_solution_prototype.test_configuration:
        class: TMSolution\ConfigurationBundle\Util\Configuration
        arguments: [%test.configuration%]
        tags:
            - { name: tm_solution_prototype.controller_configuration, applicationPath: 'admin/ala/ma/kota', entityAlias: 'product-category' }