parameters:    
    tm_solution_menu_menu_item.config: 
        base:
            allowed: true
            models:
                 get:
                        name: 'tm_solution_menu.model'
                        method: findOneById
                        result_parameter: menuItem    
        actions: 
            new:
               templates:
                    widget: 'menuitem\new.html.twig'
               models:
                    create:
                        name: 'tm_solution_menu.model'
                        method: save
                        result_parameter: menuItem
                        
               form: 
                   action: new 
                   form_type: 'TMSolution\MenuBundle\Form\MenuItemType'
               redirection: 
                    route_name: list                                     
            list:
                allowed: 
                        - xhttp
                        - inner
                templates:
                    widget: 'menuitem\query.html.twig' 
                models:
                    list:
                        name: 'tm_solution_menu.list_model'
                        method: find
                        result_parameter: menuItems 
                        data_parameter: items      
                form: 
                   form_type: 'TMSolution\MenuBundle\Form\SearchMenuItemType'
                   action: list
                   method: GET               
            typeahead:
                templates:
                    widget: 'menuitem\query.html.twig' 
                models:
                    list:
                        name: 'tm_solution_menu.typeahead'
                        method: find
                        result_parameter: items 
     
                form: 
                   form_type: 'TMSolution\MenuBundle\Form\SearchMenuItemType'
                   action: list
                   method: GET                                  
            filter:
                templates:
                    widget: 'menuitem\index.html.twig' 
     
                form: 
                   form_type: 'TMSolution\MenuBundle\Form\SearchMenuItemType'
                   method: GET
                   action: filter   
            get:
                templates:
                    widget: 'menuitem\show.html.twig'
            edit:
                templates:
                    widget: 'menuitem\edit.html.twig' 
                form: 
                   form_type: 'TMSolution\MenuBundle\Form\MenuItemType' 
                   action: edit
                models:
                    update:
                        name: 'tm_solution_menu.model'
                        method: update
                        result_parameter: menuItem
                redirection:
                    route_name: list       
            delete:
                models:
                    delete:
                        name: 'tm_solution_menu.model'
                        method: delete
                redirection:
                    route_name: list
   
   
services:
        tm_solution_menu.menu_item:
            class: TMSolution\ConfigurationBundle\Util\Configuration
            arguments: [%tm_solution_menu_menu_item.config%]
            tags:
                - { name: tm_solution_prototype.controller_configuration, application_path: 'menu', entity_alias: 'menu-item' }
        
        tm_solution_menu.model:
            class: TMSolution\ModelBundle\Util\Model
            arguments: ['@doctrine.orm.entity_manager']
            
            
        tm_solution_menu.paginator:    
            class: TMSolution\MenuBundle\Model\Paginator
            arguments: ['@knp_paginator',3 ]    
       
        tm_solution_menu.filter:
            class: TMSolution\MenuBundle\Model\Filter
            arguments: ['@lexik_form_filter.query_builder_updater']
            
        
        tm_solution_menu.list_model:
            class: TMSolution\MenuBundle\Model\Model
            arguments: ['@tm_solution_menu.model','@tm_solution_menu.filter','@tm_solution_menu.paginator' ]    
            
        tm_solution_menu.typeahead:
            class: TMSolution\MenuBundle\Model\Typeahead
            arguments: ['@tm_solution_menu.model','@tm_solution_menu.filter',10,{ 'name': 'p.name' }]    
           
       