parameters:    
    tm_solution_menu_menu_item.config: 
        base:
            allowed: true
            form: 
                   action: new 
                   form_type: 'TMSolution\MenuBundle\Form\MenuItemType'
            models:
                 get:
                        name: 'tm_solution_menu.model'
                        method: findOneById
                        result_parameter: menuItem    
        actions: 
            new:
               templates:
                    widget: 'menuitem\new.html.twig'
               models:
                    create:
                        name: 'tm_solution_menu.model'
                        method: save
                        result_parameter: menuItem    
                      
               form: 
                   action: new 
               redirection: 
                    route_name: list                                     
            list:
                templates:
                    widget: 'menuitem\index.html.twig' 
                models:
                    list:
                        name: 'tm_solution_menu.model'
                        method: search
                        result_parameter: menuItems   
            get:
                templates:
                    widget: 'menuitem\show.html.twig'
            edit:
                templates:
                    widget: 'menuitem\edit.html.twig' 
                form: 
                   action: edit
                models:
                    update:
                        name: 'tm_solution_menu.model'
                        method: update
                        result_parameter: menuItem
                redirection:
                    route_name: list    
                   
            delete:
                models:
                    delete:
                        name: 'tm_solution_menu.model'
                        method: delete
                redirection:
                    route_name: list
   
   
services:
        tm_solution_menu.menu_item:
            class: TMSolution\ConfigurationBundle\Util\Configuration
            arguments: [%tm_solution_menu_menu_item.config%]
            tags:
                - { name: tm_solution_prototype.controller_configuration, application_path: 'menu', entity_alias: 'menu-item' }
        
        tm_solution_menu.model:
            class: TMSolution\ModelBundle\Util\Model
            arguments: ['@doctrine.orm.entity_manager']
            
           
       