parameters:    
    tm_solution_wizard_view_type.config:                    
        actions: 
            new:
               allowed: true
               form: 
                   action: new 
                   form_type: 'TMSolution\WizardBundle\Form\ViewTypeType'
               templates:
                    widget: 'viewtype\new.html.twig'
               models:
                    create:
                        name: 'tm_solution_wizard.model'
                        method: save
                      
               redirection: 
                    route_name: list 
            edit:
               allowed: true
               form: 
                   action: edit 
                   form_type_class: 'TMSolution\WizardBundle\Form\ViewTypeType'
               templates:
                    widget: 'viewtype\edit.html.twig'
               models:
                    get:
                        name: 'tm_solution_wizard.model'
                        method: findOneById
                    update:
                        name: 'tm_solution_wizard.model'
                        method: update          
               redirection: 
                    route_name: list         
            list:
                allowed: true
                templates:
                    widget: 'viewtype\index.html.twig' 
                models:
                    list:
                        name: 'tm_solution_wizard.model'
                        method: search
                        result_parameter: viewTypes      
   
services:
        tm_solution_wizard.view_type:
            class: TMSolution\ConfigurationBundle\Util\Configuration
            arguments: [%tm_solution_wizard_view_type.config%]
            tags:
                - { name: tm_solution_prototype.controller_configuration, application_path: 'wizard', entity_alias: 'view-type' }
        

