
#{application_path} ={application}/{service}/{name} = app.{application}.{service}.{name}
#{entities_path} ={parent}/{parentid}/{entityAlias}
list:
    path: "{application_path}/-/{entities_path}/list/{state}"
    defaults: { _controller: "tm_solution_prototype.entity_controller:listAction", state: "",  format: ~ }
    requirements: {"application_path":".+" ,"path": ".+" }
    methods:  [GET, POST]
    options:
        expose: true    
               
new:
    path: "{application_path}/-/{entities_path}/new/{state}"
    defaults: { _controller: "tm_solution_prototype.entity_controller:newAction", state: "",  format: ~ }
    requirements: {"application_path":".+" ,"path": ".+" }
    methods:  [GET, POST]
    options:
        expose: true

create:
    path: "{application_path}/-/{entities_path}/create/{state}"
    defaults: { _controller: "tm_solution_prototype.entity_controller:createAction", state: "",  format: ~ }
    requirements: {"application_path":".+" ,"path": ".+" }
    methods:  [GET, POST]
    options:
        expose: true      

delete:
    path: "{application_path}/-/{entities_path}/delete/{id}/{state}"
    defaults: { _controller: "tm_solution_prototype.entity_controller:deleteAction", state: "",  format: ~ }
    requirements: {"application_path":".+" ,"path": ".+" }
    methods:  [GET,DELETE]
    options:
        expose: true
edit:
    path: "{application_path}/-/{entities_path}/edit/{id}/{state}"
    defaults: { _controller: "tm_solution_prototype.entity_controller:editAction", state: "",  format: ~ }
    requirements: {"application_path":".+" ,"path": ".+" }
    methods:  [GET, POST]
    options:
        expose: true          
update:
    path: "{application_path}/-/{entities_path}/update/{id}/{state}"
    defaults: { _controller: "tm_solution_prototype.entity_controller:updateAction", state: "",  format: ~ }
    requirements: {"application_path":".+" ,"path": ".+" }
    methods:  [GET, POST]
    options:
        expose: true      
get:
    path: "{application_path}/-/{entities_path}/get/{id}/{state}"
    defaults: { _controller: "tm_solution_prototype.entity_controller:getAction", state: "",  format: ~ }
    requirements: {"application_path":".+" ,"path": ".+" }
    methods:  [GET, POST]
    options:
        expose: true