
#{applicationPath} ={application}/{service}/{name} = app.{application}.{service}.{name}
#{entitiesPath} ={parent}/{parentid}/{entityAlias}
tm_solution_prototype.list:
    path: "{applicationPath}/-/{entitiesPath}/list/{state}"
    defaults: { _controller: "tm_solution_prototype.prototype_controller:listAction", state: "",  format: ~ }
    requirements: {"applicationPath":".+" ,"path": ".+" }
    methods:  [GET, POST]
    options:
        expose: true    
tm_solution_prototype.query:
    path: "{applicationPath}/-/{entitiesPath}/query/{state}"
    defaults: { _controller: "tm_solution_prototype.prototype_controller:queryAction", state: "",  format: ~ }
    requirements: {"applicationPath":".+" ,"path": ".+" }
    methods:  [GET, POST]
    options:
        expose: true                
tm_solution_prototype.new:
    path: "{applicationPath}/-/{entitiesPath}/new/{state}"
    defaults: { _controller: "tm_solution_prototype.prototype_controller:newAction", state: "",  format: ~ }
    requirements: {"applicationPath":".+" ,"path": ".+" }
    methods:  [GET, POST]
    options:
        expose: true

tm_solution_prototype.create:
    path: "{applicationPath}/-/{entitiesPath}/create/{state}"
    defaults: { _controller: "tm_solution_prototype.prototype_controller:createAction", state: "",  format: ~ }
    requirements: {"applicationPath":".+" ,"path": ".+" }
    methods:  [GET, POST]
    options:
        expose: true      

tm_solution_prototype.delete:
    path: "{applicationPath}/-/{entitiesPath}/delete/{id}/{state}"
    defaults: { _controller: "tm_solution_prototype.prototype_controller:deleteAction", state: "",  format: ~ }
    requirements: {"applicationPath":".+" ,"path": ".+" }
    methods:  [GET, POST]
    options:
        expose: true
tm_solution_prototype.edit:
    path: "{applicationPath}/-/{entitiesPath}/edit/{id}/{state}"
    defaults: { _controller: "tm_solution_prototype.prototype_controller:editAction", state: "",  format: ~ }
    requirements: {"applicationPath":".+" ,"path": ".+" }
    methods:  [GET, POST]
    options:
        expose: true          
tm_solution_prototype.update:
    path: "{applicationPath}/-/{entitiesPath}/update/{id}/{state}"
    defaults: { _controller: "tm_solution_prototype.prototype_controller:updateAction", state: "",  format: ~ }
    requirements: {"applicationPath":".+" ,"path": ".+" }
    methods:  [GET, POST]
    options:
        expose: true      
tm_solution_prototype.show:
    path: "{applicationPath}/-/{entitiesPath}/show/{id}/{state}"
    defaults: { _controller: "tm_solution_prototype.prototype_controller:showAction", state: "",  format: ~ }
    requirements: {"applicationPath":".+" ,"path": ".+" }
    methods:  [GET, POST]
    options:
        expose: true