
#{applicationPath} ={application}/{service}/{name} = app.{application}.{service}.{name}
#{entitiesPath} ={parent}/{parentid}/{entityAlias}
test_test:
    path: "test"
    defaults: { _controller: "tm_solution_prototype.test_controller:testAction",  format: ~ }
    methods:  [GET, POST]
    options:
        expose: true    
