services:
    
    flexix_prototype.application_mapper:
        class: Flexix\MapperBundle\Util\ApplicationMapper     
        arguments: [%flexix_mapper.applications%]
      
    flexix_prototype.entity_mapper: 
        class: Flexix\MapperBundle\Util\EntityMapper
        arguments: [%flexix_mapper.entities%]
    
    flexix_prototype.request_analyzer:
        class: Flexix\PathAnalyzerBundle\Util\PathAnalyzer
        arguments: ['@flexix_prototype.application_mapper', '@flexix_prototype.entity_mapper']
    
    flexix_prototype.base_configuration:
        class: Flexix\ConfigurationBundle\Util\Configuration
        arguments: [%flexix_prototype.configuration%]
    
    flexix_prototype.configuration_factory:
        class: Flexix\ControllerConfigurationBundle\Util\ControllerConfigurationFactory
        arguments: ['@flexix_prototype.base_configuration','@flexix_prototype.request_analyzer']

   
    flexix_prototype.data_adapter:
        class: Flexix\PrototypeBundle\Util\DataAdapter
   
   
    flexix_prototype.entity_controller:
        class: Flexix\PrototypeBundle\Controller\EntityController
        arguments: ['@service_container','@flexix_prototype.configuration_factory','@request_stack','@flexix_prototype.data_adapter']
        
        
    flexix_prototype.test_controller:
        class: Flexix\PrototypeBundle\Controller\TestController
        arguments: ['@service_container','@flexix_prototype.configuration_factory','@request_stack','@flexix_prototype.data_adapter']    
        
    flexix_prototype.test_controller:
        class: Flexix\PrototypeBundle\Controller\TestController
        arguments: ['@service_container','@flexix_prototype.configuration_factory']

        
    flexix_prototype.ticket:
        class: Flexix\PrototypeBundle\Util\Ticket
        arguments: []       
        shared: false
            
 
            
      