<?php

namespace TMSolution\SandboxBundle\Sample;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-04-04 at 15:47:36.
 */
class SampleLoggerTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var SampleLogger
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new SampleLogger;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers TMSolution\SandboxBundle\Sample\SampleLogger::findOneById
     * @todo   Implement testFindOneById().
     */
    public function testFindOneById() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TMSolution\SandboxBundle\Sample\SampleLogger::search
     * @todo   Implement testSearch().
     */
    public function testSearch() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TMSolution\SandboxBundle\Sample\SampleLogger::save
     * @todo   Implement testSave().
     */
    public function testSave() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TMSolution\SandboxBundle\Sample\SampleLogger::update
     * @todo   Implement testUpdate().
     */
    public function testUpdate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TMSolution\SandboxBundle\Sample\SampleLogger::delete
     * @todo   Implement testDelete().
     */
    public function testDelete() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
